# Generated by Django 3.2.9 on 2022-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_title', models.CharField(max_length=200)),
                ('invitation_writer', models.CharField(max_length=50)),
                ('invitation_input_date', models.DateTimeField(verbose_name='date published')),
                ('invitation_content', models.TextField()),
            ],
        ),
    ]
