# Generated by Django 3.2.9 on 2022-05-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invitation_content',
            new_name='invi_content',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='invitation_input_date',
            new_name='invi_input_date',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='invitation_title',
            new_name='invi_title',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='invitation_writer',
            new_name='invi_writer',
        ),
    ]
